[[customizations.user]]
name = "agent"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHJc/qpKdmC9oGJapuBjESihXq/M7PdubghcSQpj3vW4 agent@desktop"
groups = ["wheel"]

# Otherwise we get a few gigs which is obviously not enough to get anything meaningful done.
[[customizations.disk.partitions]]
mountpoint = "/"
minsize = "40 GiB"
fs_type = "xfs"
